### ISSUE TITLE
Order of operations - Q

### ISSUE THREAD

**Issue by jacobedelson** [episphere/app#1]
Do I clone the repo, make changes locally and then push it to origin or should I fork the repo? It seems that I needed to either fork or clone before pulling the repo.

**Comment by PrafulB** [comment]
@jacobedelson You typically only fork a repo when it is owned by someone else and you don't have permissions to create a branch on it/push changes to it. In this case, because it is a repository you are directly part of, cloning it locally and pushing back changes would be the way to go.
